namespace :march_madness do
  desc 'add participating march maddness teams'

  task add_teams: :environment do
    [
      [1,'Kansas','M'],
      [16, 'Austin Peay','M'],
      [8, 'Colorado','M'],
      [9, 'Connecticut', 'M'],
      [5, 'Maryland', 'M'],
      [12, 'South Dakota St', 'M'],
      [4, 'California', 'M'],
      [13, 'Hawaii', 'M'],
      [6, 'Arizona', 'M'],
      [11, 'Vanderbilt/Wichita St', 'M'],
      [3, 'Miami', 'M'],
      [14, 'Buffalo', 'M'],
      [7, 'Iowa', 'M'],
      [10, 'Temple', 'M'],
      [2, 'Villanova', 'M'],
      [15, 'UNC-Asheville', 'M'],
      [1, 'Oregon', 'E'],
      [16, 'Holy Cross/Southern', 'E'],
      [8, 'St Joes', 'E'],
      [9, 'Cincinnati', 'E'],
      [5, 'Baylor', 'E'],
      [12, 'Yale', 'E'],
      [4, 'Duke', 'E'],
      [13, 'UNC-Wilmington', 'E'],
      [6, 'Texas', 'E'],
      [11, 'UNI', 'E'],
      [3, 'Texas A&M', 'E'],
      [14, 'Green Bay', 'E'],
      [7, 'Oregon St', 'E'],
      [10, 'VCU', 'E'],
      [2, 'Oklahoma', 'E'],
      [15, 'CSU-Bakersfield', 'E'],
      [1, 'North Carolina', 'S'],
      [16, 'Florida Gulf/Farliegh Dickinson', 'S'],
      [8, 'USC', 'S'],
      [9, 'Providence', 'S'],
      [5, 'Indiana', 'S'],
      [12, 'Chattanooga', 'S'],
      [4, 'Kentucky', 'S'],
      [13, 'Stony Brook', 'S'],
      [6, 'Notre Dame', 'S'],
      [11, 'Michigan/Tulsa', 'S'],
      [3, 'West Virginia', 'S'],
      [14, 'Stephan F Austin', 'S'],
      [7, 'Wisconsin', 'S'],
      [10, 'Pittsburgh', 'S'],
      [2, 'Xavier', 'S'],
      [15, 'Weber State', 'S'],
      [1, 'Virginia', 'W'],
      [16, 'Hampton', 'W'],
      [8, 'Texas Tech', 'W'],
      [9, 'Butler', 'W'],
      [5, 'Purdue', 'W'],
      [12, 'Little Rock', 'W'],
      [4, 'Iowa St', 'W'],
      [13, 'Iona', 'W'],
      [6, 'Seton Hall', 'W'],
      [11, 'Gonzaga', 'W'],
      [3, 'Utah', 'W'],
      [14, 'Fresno St', 'W'],
      [7, 'Dayton', 'W'],
      [10, 'Syracuse', 'W'],
      [2, 'Michigan St', 'W'],
      [15, 'Middle Tennessee', 'W']
    ].each do |team|
      Team.create(ranking: team[0], name: team[1], region: team[2])
    end
  end
end
